spring:
  application:
    name: oula
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/oula}
    username: ${DB_USER:oula}
    password: ${DB_PASSWORD:oula}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
