"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { canonicalStageForDemoDealStep, demoDealProjection, demoProperties, nextDemoDealStep, previewMatch, type DemoDealStep, type IntentInput, type DemoProperty } from "../lib/model";
import { demoLabel, demoReason, demoStory } from "./demo-localization";

type Language = "ar" | "en";
type Stage = "home" | "intent" | "matching" | "passport" | "decision" | "deal" | "guardian" | "intelligence";
type Tr = { ar: string; en: string };
const tr = (lang: Language, t: Tr) => t[lang];
const stages: ReadonlyArray<{ key: Stage; label: Tr; descriptor: Tr; number: string }> = [
  { key: "home", number: "00", label: { ar: "الرؤية", en: "Vision" }, descriptor: { ar: "من الإنسان إلى العالم المبني", en: "Human to Built World" } },
  { key: "intent", number: "01", label: { ar: "افهمني", en: "Understand Me" }, descriptor: { ar: "LifeGraph + Intent", en: "LifeGraph + Intent" } },
  { key: "matching", number: "02", label: { ar: "مطابقة ذكية", en: "Smart Match" }, descriptor: { ar: "Explainable LifeFit", en: "Explainable LifeFit" } },
  { key: "passport", number: "03", label: { ar: "جواز العقار", en: "Property Passport" }, descriptor: { ar: "Truth + Provenance", en: "Truth + Provenance" } },
  { key: "decision", number: "04", label: { ar: "القرار الواعي", en: "Informed Decision" }, descriptor: { ar: "Human in Control", en: "Human in Control" } },
  { key: "deal", number: "05", label: { ar: "غرفة الصفقة", en: "Deal Room" }, descriptor: { ar: "Transaction OS", en: "Transaction OS" } },
  { key: "guardian", number: "06", label: { ar: "حارس العقار", en: "Property Guardian" }, descriptor: { ar: "Operations + Asset", en: "Operations + Asset" } },
  { key: "intelligence", number: "07", label: { ar: "الذاكرة والذكاء", en: "Reality Intelligence" }, descriptor: { ar: "Outcome + Learning", en: "Outcome + Learning" } },
];
const initialIntent: IntentInput = { budgetSar: 1200000, minBedrooms: 3, minAreaSqm: 155, preferredDistrict: "الملقا" };
const content: Record<Stage, { title: Tr; intro: Tr }> = {
  home: { title: { ar: "عالمٌ مبنيٌّ يفهم الإنسان.", en: "A built world that understands people." }, intro: { ar: "من الاحتياج الحقيقي، إلى القرار الواعي، إلى الأصل الذي يتطور مع الحياة. عُلا ليس منصة إعلانات عقارية؛ بل طبقة ذكاء وتشغيل للعالم المبني.", en: "From human needs to informed decisions and living assets. OULA is more than a property listing portal — it is an intelligence and operating layer for the built world." } },
  intent: { title: { ar: "نبدأ بحياتك، لا بقائمة عقارات.", en: "Start with your life, not a property list." }, intro: { ar: "حدّد اشتراطاتك الحقيقية بوضوح. تظل البيانات في هذه المرحلة توضيحية حتى يتصل النظام بالخلفية الفعلية.", en: "Declare real constraints and preferences. These inputs are illustrative until the actual backend is connected." } },
  matching: { title: { ar: "توصية تستطيع مناقشتها.", en: "A recommendation you can challenge." }, intro: { ar: "نميز بين الاشتراطات الإلزامية وأسباب الترتيب. الدرجات التالية محاكاة محلية وليست نتائج محرك LifeFit الفعلي.", en: "Hard constraints remain separate from ranking reasons. Scores shown here are local demo calculations, not canonical LifeFit results." } },
  passport: { title: { ar: "الحقيقة قبل الانطباع.", en: "Truth before impression." }, intro: { ar: "هوية الأصل منفصلة عن الإعلان، وكل معلومة لها مصدر ودرجة معرفة. هذا المثال لا يمثل تحققًا مستقلاً.", en: "An asset is not a listing. Every fact needs provenance. This fixture is not independently verified." } },
  decision: { title: { ar: "الذكاء يقترح. الإنسان يقرر.", en: "Intelligence proposes. Humans decide." }, intro: { ar: "انظر إلى حدود البيانات، والمقايضات، وما لا نعرفه. القرار هنا تدريبي ولا ينتج التزامًا قانونيًا.", en: "See trade-offs, limits and the unknowns. This is a simulated decision with no legal consequence." } },
  deal: { title: { ar: "صفقة لا تختزل الإنسان في زر.", en: "A transaction built around human authority." }, intro: { ar: "حالات واضحة، وخطوات تتطلب موافقة الإنسان. هذه غرفة صفقة توضيحية مستقلة عن سجلات النظام الخلفي.", en: "Explicit states and human approvals. This room is simulated and not connected to the authoritative backend." } },
  guardian: { title: { ar: "قيمة العقار تبدأ بعد الصفقة.", en: "The asset journey continues after the deal." }, intro: { ar: "نظرة إلى تشغيل الأصول والالتزامات والإشارات. التنبيهات أدناه سيناريو افتراضي، لا قياسات حساسات حقيقية.", en: "Operations, obligations and signals. All telemetry below is simulated — no physical sensors are connected." } },
  intelligence: { title: { ar: "يتذكّر الواقع، لا يتباهى بالتوقعات.", en: "Remember reality. Don't exaggerate predictions." }, intro: { ar: "نربط التوصية بالقرار والنتيجة والفجوة بينهما، دون ادعاء إثبات سببية أو نجاح نموذج لم يُختبر ميدانيًا.", en: "Connect recommendations to decisions, outcomes and reality gaps — without pretending this is causal proof or a validated deployed model." } },
};
const rtlMark = "◈";
const money = (lang: Language, amount: number) => new Intl.NumberFormat(lang === "ar" ? "ar-SA" : "en-US", { maximumFractionDigits: 0 }).format(amount) + (lang === "ar" ? " ر.س" : " SAR");
function SmallLabel({ children }: { children: React.ReactNode }) { return <span className="micro-label">{children}</span>; }
function Status({ lang, label = "DEMO" }: { lang: Language; label?: "DEMO" | "SANDBOX" | "DECLARED" | "FUTURE" }) {
  const alt: Record<typeof label, Tr> = {
    DEMO: { ar: "بيانات افتراضية", en: "Demo data" }, SANDBOX: { ar: "محاكاة فقط", en: "Sandbox only" },
    DECLARED: { ar: "مُصرّح بها / غير موثقة", en: "Declared / unverified" }, FUTURE: { ar: "قدرة مستقبلية", en: "Future capability" },
  };
  return <span className="status-tag" aria-label={tr(lang, alt[label])}><span className="status-dot" aria-hidden="true" /> {label} <span className="status-meaning">{tr(lang, alt[label])}</span></span>;
}
function PropertyCard({ p, lang, selected, onClick }: { p: DemoProperty; lang: Language; selected: boolean; onClick: () => void }) {
  return <button type="button" onClick={onClick} className={"property-card" + (selected ? " chosen" : "")} aria-pressed={selected}>
    <div className="property-visual" aria-hidden="true"><div className="building-plan"><span/><span/><span/><span/></div><small>{p.id.toUpperCase()}</small></div>
    <div className="property-info"><span className="property-area">{demoLabel(lang, p.city)} / {demoLabel(lang, p.district)}</span><strong>{demoLabel(lang, p.kind)} · {p.bedrooms} {lang === "ar" ? "غرف" : "beds"}</strong><span>{p.areaSqm} {lang === "ar" ? "م²" : "sqm"} <span aria-hidden="true">·</span> {money(lang, p.priceSar)}</span><span className="property-fact">◌ {tr(lang, { ar: "بيانات افتراضية", en: "Fictional fixture" })}</span></div>
  </button>;
}
export function OulaExperience() {
  const [lang, setLang] = useState<Language>("ar");
  const [stage, setStage] = useState<Stage>("home");
  const [intent, setIntent] = useState<IntentInput>(initialIntent);
  const [selectedId, setSelectedId] = useState<string>("demo-r01");
  const [dealStep, setDealStep] = useState<DemoDealStep>("NONE");
  const [guardianReviewed, setGuardianReviewed] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const headingRef = useRef<HTMLHeadingElement>(null);
  useEffect(() => { document.documentElement.lang = lang; document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"; }, [lang]);
  useEffect(() => {
    if (!menuOpen) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") setMenuOpen(false);
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [menuOpen]);
  const currentIndex = Math.max(0, stages.findIndex((s) => s.key === stage));
  const current = stages[currentIndex]!;
  const selected = demoProperties.find((p) => p.id === selectedId) ?? demoProperties[0]!;
  const results = useMemo(() => demoProperties.map((p) => previewMatch(intent, p)).sort((a,b) => b.score - a.score), [intent]);
  const advance = (to: Stage) => {
    setStage(to);
    setMenuOpen(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
    window.requestAnimationFrame(() => headingRef.current?.focus());
  };
  return <div className="shell">
    <a className="skip-link" href="#main-content">{tr(lang, { ar: "تجاوز إلى المحتوى", en: "Skip to content" })}</a>
    <aside className={"sidebar" + (menuOpen ? " menu-open" : "")} aria-label={tr(lang, { ar: "التنقل", en: "Navigation" })}>
      <button className="brand brand-button" type="button" onClick={() => advance("home")} aria-label={tr(lang, { ar: "العودة إلى الصفحة الرئيسية لعُلا", en: "OULA home" })}><span className="brand-glyph" aria-hidden="true">{rtlMark}</span><span><strong>عُـلا <span>OULA</span></strong><small>BUILT WORLD INTELLIGENCE</small></span></button>
      <div className="rail-heading">{tr(lang, { ar: "خارطة التجربة", en: "EXPERIENCE MAP" })}<span>{String(currentIndex + 1).padStart(2, "0")} / {String(stages.length).padStart(2, "0")}</span></div>
      <nav id="oula-stage-nav" className="stage-nav">{stages.map((s) => <button key={s.key} type="button" className={"stage-link" + (stage === s.key ? " active" : "")} aria-current={stage === s.key ? "step" : undefined} onClick={() => advance(s.key)}><span className="stage-number">{s.number}</span><span className="stage-label"><strong>{tr(lang, s.label)}</strong><small>{tr(lang, s.descriptor)}</small></span><span className="stage-arrow" aria-hidden="true">↗</span></button>)}</nav>
      <div className="rail-bottom"><div className="rail-orbit" aria-hidden="true"><i/><i/><i/></div><SmallLabel>{tr(lang, { ar: "الإنسان · المكان · المعرفة", en: "Human · Place · Intelligence" })}</SmallLabel><p>{tr(lang, { ar: "رحلة متكاملة، وقرار يمكن تفسيره.", en: "A connected journey. An explainable choice." })}</p><Status lang={lang}/></div>
    </aside>
    <div className="main-wrap">
      <div className="top-bar">
        <div className="top-breadcrumb"><button className="mobile-menu" aria-expanded={menuOpen} aria-controls="oula-stage-nav" aria-label={tr(lang, { ar: "فتح أو إغلاق قائمة المراحل", en: "Open or close stage navigation" })} onClick={() => setMenuOpen(!menuOpen)} type="button">{menuOpen ? "✕" : "☰"} <span>{tr(lang, { ar: "المراحل", en: "Stages" })}</span></button><span className="breadcrumb-orbit" aria-hidden="true">◎</span><span>{tr(lang, { ar: "تجربة النظام", en: "OULA EXPERIENCE" })}</span><span className="crumb-sep">/</span><b>{tr(lang, current.label)}</b></div>
        <div className="bar-actions"><span className="env-label">● {tr(lang, { ar: "البيئة التجريبية", en: "DEMO ENVIRONMENT" })}</span><button type="button" className="lang-switch" onClick={() => setLang(lang === "ar" ? "en" : "ar")} aria-label={lang === "ar" ? "Switch to English" : "التحويل إلى العربية"}>{lang === "ar" ? "EN" : "عربي"} <span aria-hidden="true">↔</span></button></div>
      </div>
      <main id="main-content" tabIndex={-1} className="canvas">
        <div className="page-head"><div><div className="eyebrow"><span className="eyebrow-line"/> OULA / {tr(lang, current.label).toUpperCase()} <span className="page-index">{current.number} — 07</span></div><h1 ref={headingRef} tabIndex={-1}>{tr(lang, content[stage].title)}</h1><p className="lede">{tr(lang, content[stage].intro)}</p></div><div className="page-orb" aria-hidden="true"><i/><i/><i/><b>O</b></div></div>
        {stage === "home" && <><section className="hero-band"><div className="hero-stamp"><SmallLabel>OULA | HUMAN × PLACE × INTELLIGENCE</SmallLabel><h2>{tr(lang,{ ar: "نفهم الإنسان. نقرأ المكان. نرافق القرار.", en: "Understand life. Read place. Guide decisions." })}</h2><p>{tr(lang,{ar:"هذه النسخة التأسيسية على المستودع الحقيقي. كل الأرقام والعقارات هنا بيانات خيالية تعليمية، وليست نظام وساطة مرخصًا أو متصلًا بجهة خارجية.",en:"This is the real-repository web foundation. All property and scenario figures are fictional, and no banking, public registry or brokerage integrations are live."})}</p><button type="button" className="primary-button" onClick={() => advance("intent")}>{tr(lang,{ar:"ابدأ الرحلة",en:"Begin the journey"})} <span aria-hidden="true">↗</span></button></div><div className="hero-art" aria-hidden="true"><div className="orbit-ring r1"/><div className="orbit-ring r2"/><div className="orbit-ring r3"/><div className="hero-core">O</div><div className="hero-coordinate c1">HUMAN</div><div className="hero-coordinate c2">PLACE</div><div className="hero-coordinate c3">DECISION</div></div></section><section className="overview-grid"><article><SmallLabel>01 / LIFE</SmallLabel><h3>{tr(lang,{ar:"احتياج الإنسان",en:"Human intent"})}</h3><p>{tr(lang,{ar:"ليست مجرد حقول بحث؛ بل قرار متصل بسياق الحياة.",en:"More than a filter: a decision grounded in life context."})}</p></article><article><SmallLabel>02 / REALITY</SmallLabel><h3>{tr(lang,{ar:"حقيقة العقار",en:"Asset truth"})}</h3><p>{tr(lang,{ar:"نفصل بين المعلومة المعلنة والمثبتة والمستنتجة.",en:"Distinguish declared, verified and inferred evidence."})}</p></article><article><SmallLabel>03 / TRUST</SmallLabel><h3>{tr(lang,{ar:"سلطة الإنسان",en:"Human authority"})}</h3><p>{tr(lang,{ar:"الذكاء يوصي ولا يبرم صفقة أو ينقل مالًا.",en:"Intelligence informs; humans authorize material actions."})}</p></article></section></>}
        {stage === "intent" && <section className="two-column"><div className="panel"><div className="panel-head"><SmallLabel>LIFEGRAPH LITE / DEMO</SmallLabel><Status lang={lang}/></div><h2>{tr(lang,{ar:"لنحدد ما لا يمكن التنازل عنه.",en:"Define the non-negotiables."})}</h2><div className="field-grid"><label>{tr(lang,{ar:"الميزانية القصوى (ر.س)",en:"Maximum budget (SAR)"})}<input type="number" min="100000" max="10000000" step="50000" value={intent.budgetSar} onChange={(e) => setIntent({ ...intent, budgetSar: Math.max(100000, Number(e.target.value) || 100000) })}/></label><label>{tr(lang,{ar:"الحد الأدنى للغرف",en:"Minimum bedrooms"})}<select value={intent.minBedrooms} onChange={(e) => setIntent({...intent,minBedrooms:Number(e.target.value)})}>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>{tr(lang,{ar:"الحد الأدنى للمساحة م²",en:"Minimum area sqm"})}<input type="number" min="40" max="1000" step="5" value={intent.minAreaSqm} onChange={(e) => setIntent({...intent,minAreaSqm:Math.max(40, Number(e.target.value) || 40)})}/></label><label>{tr(lang,{ar:"الحي المفضل",en:"Preferred district"})}<select value={intent.preferredDistrict ?? ""} onChange={(e) => setIntent({...intent,preferredDistrict:e.target.value})}><option value="">{tr(lang,{ar:"أي حي",en:"Any district"})}</option>{["الملقا","حطين","الصحافة"].map(x=><option key={x} value={x}>{demoLabel(lang, x)}</option>)}</select></label></div><div className="panel-actions"><button className="primary-button" onClick={() => advance("matching")}>{tr(lang,{ar:"افهم احتياجي",en:"Explore candidates"})} ↗</button></div></div><aside className="context-panel"><SmallLabel>CONTEXT ≠ CONCLUSION</SmallLabel><div className="context-sigil" aria-hidden="true">◎</div><h3>{tr(lang,{ar:"لا نخمن حياتك.",en:"We do not guess your life."})}</h3><p>{tr(lang,{ar:"الاشتراطات هنا صريحة، ولا يستخدم النموذج بيانات أسرية أو مالية حساسة دون موافقة واضحة في النظام الفعلي.",en:"Constraints here are explicit. The real product must obtain proper consent before using sensitive life or financial details."})}</p><Status lang={lang}/></aside></section>}
        {stage === "matching" && <section><div className="section-heading"><div><SmallLabel>LIFEFIT EXPLAINABILITY / DEMO</SmallLabel><h2>{tr(lang,{ar:"نتائج مرتبة مع سبب واضح",en:"Ranked results with visible reasoning"})}</h2></div><button className="text-button" onClick={() => advance("intent")}>{tr(lang,{ar:"تعديل الاحتياج",en:"Edit intent"})} ↗</button></div><div className="match-stack">{results.map((m,i)=><article className={"match-row" + (m.blocked ? " dimmed" : "")} key={m.property.id}><div className="match-rank">{String(i+1).padStart(2,"0")}</div><div className="match-data"><h3>{demoLabel(lang, m.property.kind)} — {demoLabel(lang, m.property.district)}</h3><p>{money(lang,m.property.priceSar)} · {m.property.areaSqm} {lang==="ar"?"م²":"sqm"} · {m.property.bedrooms} {lang==="ar"?"غرف":"beds"}</p><span>{m.reasons.map((reason) => demoReason(lang, reason)).join(" · ")}</span></div><div className="match-side"><span className="match-score">{m.blocked ? "—" : m.score}<small>/100</small></span><Status lang={lang}/><button disabled={m.blocked} onClick={() => {setSelectedId(m.property.id);advance("passport");}} className="minor-button">{tr(lang,{ar:"افتح الجواز",en:"Open passport"})} ↗</button></div></article>)}</div></section>}
        {stage === "passport" && <section className="two-column"><div className="panel"><div className="panel-head"><SmallLabel>ASSET IDENTITY / {selected.id}</SmallLabel><Status lang={lang} label="DECLARED"/></div><h2>{demoLabel(lang, selected.kind)} — {demoLabel(lang, selected.district)}</h2><p>{demoStory(lang, selected)}</p><div className="fact-grid"><div><SmallLabel>{tr(lang,{ar:"السعر المعلن",en:"Declared asking price"})}</SmallLabel><strong>{money(lang,selected.priceSar)}</strong><Status lang={lang} label="DECLARED"/></div><div><SmallLabel>{tr(lang,{ar:"المساحة",en:"Declared area"})}</SmallLabel><strong>{selected.areaSqm} {lang==="ar"?"م²":"sqm"}</strong><Status lang={lang} label="DECLARED"/></div><div><SmallLabel>{tr(lang,{ar:"عدد الغرف",en:"Bedrooms"})}</SmallLabel><strong>{selected.bedrooms}</strong><Status lang={lang} label="DECLARED"/></div><div><SmallLabel>{tr(lang,{ar:"السجل والتحقق",en:"Official registry verification"})}</SmallLabel><strong>{tr(lang,{ar:"غير متاح",en:"Unavailable"})}</strong><Status lang={lang} label="SANDBOX"/></div></div><div className="panel-actions"><button onClick={() => advance("decision")} className="primary-button">{tr(lang,{ar:"انتقل إلى تقييم القرار",en:"Evaluate this choice"})} ↗</button></div></div><aside className="context-panel"><SmallLabel>PROPERTY ≠ LISTING</SmallLabel><div className="context-sigil" aria-hidden="true">◈</div><h3>{tr(lang,{ar:"جواز يحمل الحقيقة، لا الادعاء.",en:"A passport for evidence, not claims."})}</h3><p>{tr(lang,{ar:"هذه المعطيات افتراضية. عند ربط النواة الفعلية، ستظهر مصادر كل حقيقة وتاريخها وحالتها دون تحويل الظنون إلى حقائق.",en:"This fictional record will be replaced with traceable domain facts. Inferred or declared data is never silently promoted to verified truth."})}</p><div className="mini-divider"/><SmallLabel>PROVENANCE STATES</SmallLabel><p>DECLARED · OBSERVED · CALCULATED · ESTIMATED · AI_INFERRED · DISPUTED · EXPIRED</p></aside></section>}
        {stage === "decision" && <section className="two-column"><div className="panel"><div className="panel-head"><SmallLabel>HUMAN DECISION / DEMO</SmallLabel><Status lang={lang}/></div><h2>{tr(lang,{ar:"قرار أكبر من درجة المطابقة.",en:"A decision larger than a score."})}</h2><p>{tr(lang,{ar:"الاختيار الأول لا يعني أنه مؤكد الأفضل. نقارن المعايير المعروفة ونتوقف عند البيانات غير المتاحة.",en:"The highest demo score is not necessarily the best decision. Compare what is known and pause at missing evidence."})}</p><div className="decision-check"><div><b>01</b><span>{tr(lang,{ar:"الاشتراطات الإلزامية",en:"Hard constraints"})}</span><strong>{tr(lang,{ar:"قابلة للفحص",en:"Checkable"})}</strong></div><div><b>02</b><span>{tr(lang,{ar:"المستندات والتوثيق",en:"Documentary verification"})}</span><strong>{tr(lang,{ar:"غير مثبتة",en:"Unverified"})}</strong></div><div><b>03</b><span>{tr(lang,{ar:"المخاطر وعدم اليقين",en:"Risks and uncertainty"})}</span><strong>{tr(lang,{ar:"للمراجعة البشرية",en:"Human review"})}</strong></div></div><div className="panel-actions"><button className="primary-button" onClick={() => advance("deal")}>{tr(lang,{ar:"افتح غرفة الصفقة التجريبية",en:"Open simulated Deal Room"})} ↗</button></div></div><aside className="context-panel"><SmallLabel>NO AUTOMATIC DECISION</SmallLabel><div className="context-sigil">↗</div><h3>{tr(lang,{ar:"سلطة القرار لك.",en:"You retain decision authority."})}</h3><p>{tr(lang,{ar:"لا عقود موقعة، ولا طلب تمويل، ولا دفع فعلي، ولا إجراءات حكومية من هذه الشاشة.",en:"No signed contract, financing, payment, or government action is initiated by this screen."})}</p><Status lang={lang} label="SANDBOX"/></aside></section>}
        {stage === "deal" && <section className="two-column"><div className="panel"><div className="panel-head"><SmallLabel>TRANSACTION OS / DEMO</SmallLabel><Status lang={lang} label="SANDBOX"/></div><h2>{tr(lang,{ar:"خطوات واضحة وموافقات واعية.",en:"Explicit stages and conscious approvals."})}</h2><div className="canonical-state"><SmallLabel>{tr(lang,{ar:"إسقاط المرحلة المرجعية",en:"Canonical stage projection"})}</SmallLabel><strong>{canonicalStageForDemoDealStep(dealStep)}</strong><span>{tr(lang,{ar:"عرض توضيحي فقط؛ لا يغيّر حالة الخادم.",en:"Presentation only; does not mutate backend state."})}</span></div><div className="deal-line" aria-live="polite">{[["NONE", "01", {ar:"بداية التجربة",en:"Start"}],["VIEWING_REQUESTED","02",{ar:"طلب معاينة توضيحي",en:"Demo viewing"}],["OFFER_PREPARED","03",{ar:"عرض توضيحي",en:"Demo offer"}],["HUMAN_APPROVED","04",{ar:"موافقة بشرية توضيحية",en:"Demo human approval"}]].map(([code,num,label])=><div key={String(code)} className={"deal-state"+(dealStep===code?" current":"")}><span>{String(num)}</span><strong>{tr(lang,label as Tr)}</strong><small>{dealStep===code?tr(lang,{ar:"الحالة الحالية",en:"Current stage"}):"SANDBOX"}</small></div>)}</div><div className="panel-actions"><button className="primary-button" disabled={dealStep==="HUMAN_APPROVED"} onClick={()=>setDealStep(nextDemoDealStep(dealStep))}>{dealStep==="NONE"?tr(lang,{ar:"طلب معاينة تجريبية",en:"Request demo viewing"}):dealStep==="VIEWING_REQUESTED"?tr(lang,{ar:"جهّز عرضًا تجريبيًا",en:"Prepare a demo offer"}):dealStep==="OFFER_PREPARED"?tr(lang,{ar:"أؤكد الموافقة التجريبية",en:"Approve simulated offer"}):tr(lang,{ar:"اكتمل السيناريو التجريبي",en:"Demo completed"})} ↗</button><button className="text-button" onClick={()=>setDealStep("NONE")}>{tr(lang,{ar:"إعادة ضبط",en:"Reset"})}</button></div></div><aside className="context-panel"><SmallLabel>AUDIT + AUTHORITY</SmallLabel><div className="context-sigil">⌁</div><h3>{tr(lang,{ar:"التجربة لا تنشئ صفقة حقيقية.",en:"No real transaction is created."})}</h3><p>{tr(lang,{ar:"الحالة هنا في ذاكرة المتصفح فقط. عمليات الصفقة الفعلية ستستخدم ماكينة حالات Java مع توثيق وإذن وصلاحيات كاملة.",en:"State is in browser memory only. The Java backend will own real transition controls, durable audit and authorization."})}</p><p className="projection-note">{tr(lang, demoDealProjection[dealStep])}</p><Status lang={lang} label="SANDBOX"/></aside></section>}
        {stage === "guardian" && <section className="two-column"><div className="panel"><div className="panel-head"><SmallLabel>ASSET GUARDIAN / FUTURE LIVE INTEGRATION</SmallLabel><Status lang={lang} label="SANDBOX"/></div><h2>{tr(lang,{ar:"لأصلٍ يبقى تحت الرعاية.",en:"Care beyond acquisition."})}</h2><div className="guardian-row"><div className="guardian-symbol" aria-hidden="true">◎</div><div><strong>{tr(lang,{ar:"سيناريو فحص تكييف",en:"HVAC inspection scenario"})}</strong><p>{tr(lang,{ar:"إشارة تشغيل توضيحية، لا تأتي من جهاز متصل.",en:"Illustrative signal, not connected sensor telemetry."})}</p></div><Status lang={lang} label="SANDBOX"/></div><div className="panel-actions"><button className="primary-button" onClick={()=>setGuardianReviewed(!guardianReviewed)}>{guardianReviewed?tr(lang,{ar:"إلغاء المراجعة التجريبية",en:"Reset demo review"}):tr(lang,{ar:"اعتماد مراجعة بشرية تجريبية",en:"Review hypothetical signal"})} ↗</button></div><p className="form-note">{guardianReviewed?tr(lang,{ar:"سُجلت موافقة توضيحية محليًا؛ لا أمر عمل حقيقي.",en:"Browser-only simulated approval; no real work order."}):tr(lang,{ar:"يشترط التنفيذ الواقعي سياسات وصلاحيات وأدلة معتمدة.",en:"Real execution requires authority, verified evidence and policy."})}</p></div><aside className="context-panel"><SmallLabel>PROPERTY VITAL SIGNS</SmallLabel><div className="context-sigil">∿</div><h3>{tr(lang,{ar:"نرى الحالة… ونعترف بالمجهول.",en:"Observe state, preserve unknowns."})}</h3><p>{tr(lang,{ar:"لن نعرض مؤشر صحة أو إشغالًا مؤكّدًا عندما لا تتوفر قياسات وأدلة تشغيل موثوقة.",en:"No manufactured health or occupancy score without sufficiently supported operational data."})}</p><Status lang={lang} label="FUTURE"/></aside></section>}
        {stage === "intelligence" && <><section className="hero-band final-band"><div className="hero-stamp"><SmallLabel>REALITY MEMORY / BUILT WORLD LAYER</SmallLabel><h2>{tr(lang,{ar:"من القرار إلى الواقع، ومن الواقع إلى المعرفة.",en:"From decision to reality. From reality to learning."})}</h2><p>{tr(lang,{ar:"نواة عُلا الفعلية تحتفظ بالتوصية والقرار والنتيجة وفجوة الواقع. أما النماذج الهندسية واسعة النطاق والمحاكاة الحضرية فهي مسار علمي مستقبلي لم يثبت تشغيليًا بعد.",en:"The real OULA backend models recommendations, decisions, outcomes and reality gaps. Large-scale engineering and city simulations remain research, not deployed validated capabilities."})}</p><Status lang={lang} label="FUTURE"/></div><div className="hero-art" aria-hidden="true"><div className="orbit-ring r1"/><div className="orbit-ring r2"/><div className="orbit-ring r3"/><div className="hero-core">O</div></div></section><div className="closing-note"><SmallLabel>OULA | BUILT WORLD INTELLIGENCE & OPERATING LAYER</SmallLabel><p>{tr(lang,{ar:"نشأ في المملكة العربية السعودية. وصُمم ليفهم العالم المبني.",en:"Born in Saudi Arabia. Built to understand the built world."})}</p><button className="text-button" onClick={()=>{setDealStep("NONE");setGuardianReviewed(false);setIntent(initialIntent);setSelectedId("demo-r01");advance("home");}}>{tr(lang,{ar:"أعد بدء العرض",en:"Restart the experience"})} ↗</button></div></>}
        <footer className="canvas-footer"><span>OULA · INTERNAL WEB FOUNDATION v0.1</span><span>{tr(lang,{ar:"البيانات المعروضة خيالية وليست موثقة أو صفقات حقيقية.",en:"Fictional data, not real property evidence or transactions."})}</span></footer>
      </main>
    </div>
  </div>;
}
